name: Deploy

on:
  push:
    tags:
      - 'v*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Build and push Docker image
      run: |
        VERSION=$(git describe --tags --always)
        docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/go-devops-app:$VERSION .
        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/go-devops-app:$VERSION
        docker tag ${{ secrets.DOCKER_HUB_USERNAME }}/go-devops-app:$VERSION ${{ secrets.DOCKER_HUB_USERNAME }}/go-devops-app:latest
        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/go-devops-app:latest